### ISSUE TITLE
1.1.30.1 - \MT-compiled exe Not running on Win 10

### ISSUE THREAD

**Issue by TaurusPrime** [HotKeyIt/ahkdll-v1-release#10]
Hi,

I tried the following:

1) Visual Studio Compile https://github.com/HotKeyIt/ahkdll with \MT (i need it for an installer)

2) Copy the compiled exe to \Compiler\

3) Compile ahk-Code: "MsgBox test" without compression & with the new exe

It's not working. But if the exe is used next to the script with same name, it's working. So the compiler seem to not work with \MT-compiled exes

Any solution?

**Comment by HotKeyIt** [comment]
Did you change lib_pcre to MT as well?
Do you use the exe or SC.bin?

**Comment by TaurusPrime** [comment]
I replaced "AutoHotkey.vcxproj" and "source\lib_pcre\lib_pcre.vcxproj": "MultiThreadedDLL" to "MultiThreaded"

The exe is running without problems. But if i compile it with the ahk Compiler, it's not working anymore. 

I am using the final exe from Visual Studio.

**Comment by HotKeyIt** [comment]
I have now included MT version, compiled as well as configuration files for source ;)

**Comment by TaurusPrime** [comment]
Perfect! Now it's working. Thank you so much!!!
