### ISSUE TITLE
Compiler/Lib/AhkThread.ahk  should be expression-if ?

### ISSUE THREAD

**Issue by mmikeww** [HotKeyIt/ahkdll-v1-release#13]
https://github.com/HotKeyIt/ahkdll-v1-release/blob/9479d7c978cef92e6b599d63ef4a5238eabb5f03/Compiler/Lib/AhkThread.ahk#L5

should be ?

` if (obj="") `

**Comment by HotKeyIt** [comment]
Thanks, fixed.
