### ISSUE TITLE
AutoHotkeySC.bin in Win32a blocked by Windows Defender

### ISSUE THREAD

**Issue by bashenk** [HotKeyIt/ahkdll-v1-release#14]
[AutoHotkeySC.bin](https://github.com/HotKeyIt/ahkdll-v1-release/blob/master/Win32a/AutoHotkeySC.bin) is blocked by Windows Defender.

I know I could just exclude it from Windows Defender, but [virus total also detects 8 engines](https://www.virustotal.com/gui/file/6b63844df208464d69d7283d04ca50de55e9192e173f7ee903242afd97ec041b/detection) in the file.

The same file from commit 04a053f5b2b2026028189786cc5cbc72775d2121 [gives 5 engines](https://www.virustotal.com/gui/file/624086a532bfe0ad1fabab0f9f5c0077b1cbf0a5c0a152349499cb2cf86731a4/detection), which is perhaps why Windows Defender hasn't blocked it automatically.

Any idea why this is the case?

**Comment by HotKeyIt** [comment]
I have no idea what the cause is, however latest version seems to be fine with windows defender.
