### ISSUE TITLE
Virus Total Check

### ISSUE THREAD

**Issue by homezonebenny** [HotKeyIt/ahkdll-v1-release#19]
This project contains a lot of (hopefully) false positive virus messages on www.virustotal.com!
Please re-write the code so that this will not be the case!
Interesstingly even mpress.exe throws virus messages though. :-\
But if you can fix everything else to not throwing virus messages it would be great!

**Comment by HotKeyIt** [comment]
See https://www.autohotkey.com/boards/viewtopic.php?f=17&t=62266
All we can do is to report the false-positives to the AV vendors.
