### ISSUE TITLE
CONTINUABLE EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by zcoolerahk** [HotKeyIt/ahkdll-v1-release#4]
Hi HotKeyIt!

I get this error message when opening a script of mine which Im not getting if using the AHK v1.1. 
## AutoHotkey

Error: CONTINUABLE EXCEPTION_ACCESS_VIOLATION

Mouse and Keyboard hooks have been disabled.
-  Press yes to exit thread and continue execution.
-  Press no to continue thread (debug).
-  Press cancel to exit application.

Exception was caused in thread id: 3708
Line: 35
## Ja   Nej   Avbryt   

Regards
zcooler

**Comment by HotKeyIt** [comment]
See pm reply on ahkscript.org, the problem was in your script.
