### ISSUE TITLE
Directive SetVersion is not working in 32bit - Ansi version

### ISSUE THREAD

**Issue by dmacoder** [HotKeyIt/ahkdll-v1-release#6]
Could you test compiling Ahk2Exe.ahk to Ahk2Exe.exe ?
Directive SetVersion is not working in 32bit - Ansi version
Error in #include VersionRes.ahk
Out of memory 
026: while addr < addrLimit
027: {
028 : size := (NumGet(addr+0, "Ushort") + 3) &~3, blabla~~

Build the Environment
OS : WINDOWS 10 HOME (1511 10586.218) 64bit 
AHK version : AUTOHOTKEY_H ANSI 32-bit 1.1.23.05-H006

**Comment by HotKeyIt** [comment]
Try using AutoHotkey.exe \Win32a as Base File (.bin).

**Comment by dmacoder** [comment]
That's not working too.
Only Unicode version works fine.
Directive SetVersion is not working in Ansi version.

**Comment by dmacoder** [comment]
Could you test compiling Ahk2Exe.ahk to Ahk2Exe.exe by using Ansi Version?
Directive SetVersion is not working in 32bit - Ansi version

```
class VersionRes
{
    Name := ""
    ,Data := ""
    ,IsText := true
    ,DataSize := 0
    ,Children := []

    __New(addr := 0)
    {
        if !addr
            return this
        wLength := NumGet(addr+0, "UShort"), addrLimit := addr + wLength, addr += 2
        ,wValueLength := NumGet(addr+0, "UShort"), addr += 2
        ,wType := NumGet(addr+0, "UShort"), addr += 2
        ;Need to modify below
                szKey := StrGet(addr), addr += 2*(StrLen(szKey)+1), addr := (addr+3)&~3

        ObjSetCapacity(this, "Data", size := wValueLength*(wType+1))
         ;Check Value is Correct
msgbox,% "wLength : " wLength "`nwValueLength : " wValueLength "`nszKey : " szKey "`nwType : " wType
                ;szKey Value is not Correct.  as follows Unicode Ver : VS_VERSION_INFO ,  Ansi ver : V
                ;so occuring out of memory

        this.Name := szKey
        ,this.DataSize := wValueLength
        ,this.IsText := wType
        ,DllCall("msvcrt\memcpy", "ptr", this.GetDataAddr(), "ptr", addr, "ptr", size, "cdecl"), addr += size, addr := (addr+3)&~3
         ;if wType
        ;ObjSetCapacity(this, "Data", -1)
        while addr < addrLimit
        {
            size := (NumGet(addr+0, "UShort") + 3) & ~3
            ,this.Children.Insert(new VersionRes(addr))
            ,addr += size
        }
    }

    _NewEnum()
    {
        return this.Children._NewEnum()
    }

    AddChild(node)
    {
        this.Children.Insert(node)
    }

    GetChild(name)
    {
        for k,v in this
            if v.Name = name
                return v
    }

    GetText()
    {
        if this.IsText
            return this.Data
    }

    SetText(txt)
    {
        this.Data := txt
        ,this.IsText := true
        ,this.DataSize := StrLen(txt)+1
    }

    GetDataAddr()
    {
        return ObjGetAddress(this, "Data")
    }

    Save(addr)
    {
        orgAddr := addr
        ,addr += 2
        ,NumPut(ds:=this.DataSize, addr+0, "UShort"), addr += 2
        ,NumPut(it:=this.IsText, addr+0, "UShort"), addr += 2
        ,addr += 2*StrPut(this.Name, addr+0, "UTF-16")
        ,addr := (addr+3)&~3
        ,realSize := ds*(it+1)
        ,DllCall("msvcrt\memcpy", "ptr", addr, "ptr", this.GetDataAddr(), "ptr", realSize, "cdecl"), addr += realSize
        ,addr := (addr+3)&~3
        for k,v in this
            addr += v.Save(addr)
        size := addr - orgAddr
        ,NumPut(size, orgAddr+0, "UShort")
        return size
    }
}

```

---

;@Ahk2Exe-SetName         Ahk2Exe
;@Ahk2Exe-SetDescription  AutoHotkey Script Compiler
;@Ahk2Exe-SetCopyright    Copyright (c) since 2004
;@Ahk2Exe-SetCompanyName  AutoHotkey
;@Ahk2Exe-SetOrigFilename Ahk2Exe.ahk
;@Ahk2Exe-SetMainIcon     Ahk2Exe.ico

## ;@Ahk2Exe-SetVersion 1.0.0.1

I had to check value is correct.
msgbox,% "wLength : " wLength "`nwValueLength : " wValueLength "`nszKey : " szKey "`nwType : " wType
szKey Value is not same as follows 
Unicode Ver : VS_VERSION_INFO
Ansi ver : V
So occuring out of memory.
Error in #include VersionRes.ahk
 Out of memory 
 026: while addr < addrLimit
 027: {
 028 : size := (NumGet(addr+0, "Ushort") + 3) &~3, blabla~~

I modify below and szKey Value is correct.
szKey := StrGet(addr,"UTF-16")
and then Compilation is complete without out of memory.
Set Version is replaced correctly.
But, Set Description is not correct as follows. (Such as Text is not correct ; likes wType=1)
畁潴潈歴祥匠牣灩⁴潃灭汩牥䘀潲卭牴慥Ɑ摇灩畬屳摇灩牃慥@FileVersion 
This script is difficult to understand. I can't fix it anymore
Can you do fix it?

**Comment by HotKeyIt** [comment]
That should be fixed now ;)

**Comment by dmacoder** [comment]
You did a good job! :D
