### ISSUE TITLE
struct() and _struct

### ISSUE THREAD

**Issue by nnnik** [HotKeyIt/ahkdll-v1-release#8]
I keep finding references to struct() the only thing I can find is the class _struct.
Where would I find struct() and where would people be able to get it?
Where do you link towards it in your repository?

**Comment by HotKeyIt** [comment]
https://autohotkey.com/board/topic/55150-class-structfunc-sizeof-updated-010412-ahkv2/

I don't link it since it is build-in in AutoHotkey_H, to avoid confusion.
