### ISSUE TITLE
1.1.30.1 - Not running on Win 10

### ISSUE THREAD

**Issue by TaurusPrime** [HotKeyIt/ahkdll-v1-release#9]
Hi,

I tried the following:

1) Download and unzip
2) ahk-Code: MsgBox test
3) Compile without compression & with Win32w\AutoHotkey.exe

4) it's not running. I got this error in windows eventlog:

 testx.exe 
   1.1.30.1 
   5c3291cf 
   ntdll.dll 
   10.0.17134.471 
   fe852bc4 
   c0000005 
   00045d15 
   2ff0 
   01d4c2c3974561ff 
   E:\Test\testx.exe 
   C:\WINDOWS\SYSTEM32\ntdll.dll 

Any solution? 

Win 10 x64 1803, AV only Windefender, but there is no message and deactivation doesn't help.

**Comment by HotKeyIt** [comment]
Should be fixed now, thanks for reporting ;)

**Comment by TaurusPrime** [comment]
Still not working. Could you fix it?
